on:
  release:
    types: [published]

name: Publish
jobs:
  build:
    name: Publish Gaucho
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - run: sudo dpkg --add-architecture i386
      - run: sudo apt update
      - run: sudo apt install icnsutils graphicsmagick rpm wine-stable wine32
      - name: Build project
        run: npm run dist-all
      - name: Upload files
        uses: JasonEtco/upload-to-release@master
        with:
          args: dist/Gaucho*
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
